### ISSUE TITLE
[feature] AZERTY keyboard

### ISSUE THREAD

**Issue by TeezeR-22** [MrNerdy42/keywizard-fabric#1]
Hello,
would it be possible to add in the pages the azerty keyboard ?

![image](https://user-images.githubusercontent.com/45720987/80870379-5b278d80-8ca6-11ea-929b-8459efeae275.png)

**Comment by MrNerdy42** [comment]
@TeezeR-22 Good news! Development is for this mod is back under way and this feature is at the top of my list. I'm developing the initial version in Fabric and will be porting to Forge later.

**Comment by MrNerdy42** [comment]
@TeezeR-22 How's this for an AZERTY keyboard? Keyboard Wizard will now automatically reflect the keyboard layout that is selected in your OS when the game is launched.

![Screenshot 2022-01-24 150730](https://user-images.githubusercontent.com/21129725/150856599-b1e1168a-4fd7-49e9-8f74-0d89a5953132.png)
