### ISSUE TITLE
Ability to unbind keys from other mods that has default keys

### ISSUE THREAD

**Issue by EGOIST1372** [MrNerdy42/keywizard-fabric#3]
Ability to unbind keys from other mods that has default keys.
like put an delete key beside every mods keybind so we can unbind the default keys. for instance I have a mod that I don't use often and I want it to be unbind till when I needed it so then I can go and set a key for it later. this way I save a key from binding for no reason to a mod that I don't use for now

**Comment by EGOIST1372** [comment]
It seems that it is possible with ESC key
just found out
sorry

**Comment by MrNerdy42** [comment]
I'm going to disagree with you, actually. 

Being able to unbind keys with ESC is a side effect of how Minecraft's binding system works. I actually didn't even know that was possible until you told me, but it makes sense if you look at the code.

I'd like to have a more intuitive way to unbind keys, like a "Clear Binding" button. Keyboard Wizard has had this feature in previous versions, and I have plans to add it again. I'm going to re-open this issue and mark it as a feature request. It'll be closed when I add the button.

Thanks for the help! Cheers!

**Comment by EGOIST1372** [comment]
looking forward to that
thanks

**Comment by MrNerdy42** [comment]
@EGOIST1372 This feature is available on the latest version!
