### ISSUE TITLE
Licensing question for fork in modpack

### ISSUE THREAD

**Issue by asanetargoss** [MrNerdy42/keywizard-fabric#4]
Hey there! I'm the developer of Hardcore Alchemy: Magic With Consequences, a MultiMC-based modpack for Minecraft 1.10.2. As part of modpack development, I forked Keyboard Wizard in accordance with its license, to fix a crash. The fork is here:

https://github.com/asanetargoss/Keyboard-Wizard

With Curseforge support for Linux seeming likely, I have been exploring the possibility of uploading HcA to Curseforge, but I noticed that the 1.10.2 version of Keyboard Wizard has been removed from Curseforge, and I would ideally like to use the mod in the Curseforge version of the pack with the crash fix I added. With that in mind, I have the following questions:

- Are you open to the idea of a 1.10 version of your mod being on Curseforge in some fashion?
- If the above is true, would it be alright for me to create a Curseforge page for my fork?
- If a fork with its own Curseforge page, what is your preferred revenue split?

**Comment by MrNerdy42** [comment]
Hello! It makes me happy that you enjoy my mod enough to resurrect the 1.10 version :)

GitHub issues aren't really the place for discussing licensing. Mind if I shoot you a PM on CurseForge?
